from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.vectorstores import FAISS

from app.exceptions import ModelError, RetrievalError, ValidationError
from app.logger import logger

class NewsSearchAgent:
    def __init__(self, vectorstore: FAISS | None) -> None:
        """
        Initialize the NewsSearchAgent with a vectorstore and LLM.

        Args:
            vectorstore (FAISS | None): Pre-built FAISS vectorstore.

        Raises:
            ValidationError: If vectorstore is None.
            ModelError: If LLM initialization fails.
        """
        if vectorstore is None:
            raise ValidationError("vectorstore cannot be None")
        self.vectorstore = vectorstore
        try:
            self.model = self.load_model()
        except Exception as e:
            raise ModelError(f"Failed to initialize LLM: {e}") from e

    def load_model(self):
        """
        Load the OpenAI Chat LLM (gpt-4o-mini) for generating responses.

        Returns:
            ChatOpenAI: Initialized language model.

        Raises:
            ModelError: If the model fails to load (e.g., missing API key).
        """
        try:
            return ChatOpenAI(
                model="gpt-4o-mini",
                temperature=0,
            )
        except Exception as e:
            raise ModelError(
                "Failed to load ChatOpenAI model. Ensure OPENAI_API_KEY is set."
            ) from e

    def ask(self, query: str) -> str:
        """
        Process a user query, retrieve relevant documents, and generate an answer.
        Implements a retrieval loop to progressively fetch more documents if needed.

        Args:
            query (str): The user's question.

        Returns:
            str: The answer generated by the agent, or a clarification message.

        Raises:
            ValidationError: If the query is empty or too short.
            RetrievalError: If vectorstore retrieval fails.
            ModelError: If LLM fails or prompt formatting fails.
        """
        if not query or not str(query).strip():
            raise ValidationError("Query cannot be empty")
        if len(query.strip()) < 10:
            raise ValidationError(
                "Query too short. Please provide at least 10 characters."
            )

        accumulated_docs = []
        k = 2
        max_rounds = 4  # Prevent infinite LLM loops

        for _ in range(max_rounds):
            try:
                retriever = self.vectorstore.as_retriever(
                    search_type="similarity",
                    search_kwargs={"k": k},
                )
            except Exception as e:
                raise RetrievalError(f"Failed to create retriever: {e}") from e

            try:
                docs = retriever.invoke(query)
            except Exception as e:
                raise RetrievalError(f"Failed to retrieve documents: {e}") from e

            if docs:
                accumulated_docs.extend(docs)

            try:
                context_text = (
                    "\n".join([doc.page_content[:500] for doc in accumulated_docs])
                    if accumulated_docs
                    else "NO_CONTEXT_FOUND"
                )
            except (AttributeError, KeyError) as e:
                raise RetrievalError(f"Invalid document format: {e}") from e

            decision_prompt_template = """
                You are a professional news analyst.

                Based on the context and question, decide the next action.

                Context:
                {context}

                Question:
                {question}

                Rules:
                - If you have enough information, provide the final answer.
                - If the question is unclear, respond ONLY with: ACTION: CLARIFY
                - If no relevant info exists, respond ONLY with: ACTION: RETRIEVE_MORE

                Response:
            """

            try:
                prompt = ChatPromptTemplate.from_template(decision_prompt_template)
                formatted_prompt = prompt.format(
                    context=context_text,
                    question=query,
                )
            except Exception as e:
                raise ModelError(f"Failed to format prompt: {e}") from e

            try:
                result = self.model.invoke(formatted_prompt)
                response_text = (
                    result.content.strip()
                    if hasattr(result, "content")
                    else str(result).strip()
                )
            except Exception as e:
                raise ModelError(
                    f"LLM invocation failed. Check API key and network: {e}"
                ) from e

            if "ACTION:" in response_text.upper():
                action = response_text.split("ACTION:")[-1].strip().upper()

                if action == "RETRIEVE_MORE":
                    logger.info(
                        f"LLM indicated more context is needed. "
                        f"Increasing k from {k} to {k*2} and retrieving "
                        f"additional documents."
                    )
                    k *= 2
                    continue

                if action == "CLARIFY":
                    return "The question appears unclear. Please clarify your request."

                return "No relevant information found."

            if "Answer:" in response_text:
                response_text = response_text.split("Answer:")[-1].strip()

            return response_text or "No relevant information found."

        return "No relevant information found."